language: python
python:
  - 3.7
dist: xenial
install:
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off pytest-cov pytest-faulthandler codecov pytest-bdd
  - pip install -e .
script:
  # run tests
  - pytest --cov-report=xml --cov=rdfsync

after_success:
  - codecov
